platform :ios, '8.0'
use_frameworks!

target 'MobileTest' do
    pod 'Alamofire', '3.0.0'
    pod 'SwiftyJSON', '2.3.1'
    pod 'QRCodeReader.swift', '5.4.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'Cosmos', '~> 1.2'
end

